name: azizapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # 3D Animation and Graphics
  flutter_cube: ^0.1.1
  model_viewer_plus: ^1.7.2
  
  # Navigation and State Management
  go_router: ^14.2.7
  provider: ^6.1.2
  
  # Animations
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.0
  
  # UI Components
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.1.0
  
  # Storage and Preferences
  shared_preferences: ^2.2.3
  
  # Icons
  iconsax: ^0.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/animations/
